name: build asciidoc

on:
  push:
      branches:
          - main
jobs:
  asciidoc_build:
    runs-on: ubuntu-18.04
    name: Build Asciidoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build HTML
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -D . --backend=html5 -o index.html document.adoc"

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v1
        with:
          name: HTML document
          path: index.html
      - name: Push to pages 
        run: |
          git config --global user.name furioncycle
          git config --global user.email admarquez21@gmail.com
          git commit -am "Updating Pages"
          git add index.html
          git push
          
      - name: Build PDF
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf -a allow-uri-read -D . document.adoc"

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF document
          path: document.pdf
